name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout Code
            uses: actions/checkout@v3

        -   name: Set up Node.js
            uses: actions/setup-node@v3
            with:
                node-version: 16

        # Install dependencies for frontend
        -   name: Install Frontend Dependencies
            working-directory: ./frontend
            run: npm install

        # Install dependencies for backend
        -   name: Install Frontend Dependencies
            working-directory: ./backend
            run: npm install

        -   name: Install dependencies
            run: npm install

        -   name: Run backend tests
            working-directory: ./backend
            run: npm test